app_auth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from .forms import LoginForm
from django.urls import path
# from .views import CustomLogoutView

app_name = "app_auth"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path("signin/", LoginView.as_view(template_name="app_auth/login.html"), name="signin"),
    # path("signin/", LoginView.as_view(template_name="app_auth/login.html", form_class=LoginForm, redirect_authenticated_user=True), name="signin"),
    path("logout/", LogoutView.as_view(template_name="app_auth/logout.html"), name="logout"),
    # path("logout/", CustomLogoutView.as_view(), name="logout"),
]

hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path("", include("quotes.urls")),
    path("auth/", include("app_auth.urls")),
    path("admin/", admin.site.urls),
    # path("users/", include("users.urls")),
]

quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="/"),
    path("<int:page>", views.main, name="root_paginate"),
]

app_auth/models.py
from django.db import models

# Create your models here.

quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None,
                               null=True)
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

# Create your models here.

app_auth/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import TextInput, CharField, EmailInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=30, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

app_auth/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import View
from .forms import RegisterForm


class RegisterView(View):
    template_name = "app_auth/register.html"
    form_class = RegisterForm

    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return redirect(to="quotes:index")
    #     return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request,f"Hello {username}! Your account successfully created!")
            return redirect(to="app_auth:signin")
        return render(request, self.template_name, {"form": form})

quotes/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .utils import get_mongodb
# from django.contrib.auth.decorators import login_required # потрібний для правильної логінізації


# @login_required
def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html",
                  context={"quotes": quotes_on_page})

users/views.py
from django.shortcuts import render

# Create your views here.

app_auth/templates/app_auth/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h1>Login User</h1>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message}}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

app_auth/templates/app_auth/logout.html
{% extends 'quotes/base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1>Please come back</h1>
    </div>

{% endblock %}

app_auth/templates/app_auth/register.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h1>Register User</h1>

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Repeat password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>HomeWork</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes of Authors</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                <a class="nav-link" href="{% url 'app_auth:signup' %}">Add new quote</a>
                <a class="nav-link" href="{% url 'app_auth:signup' %}">Add new author</a>
                <a class="nav-link" href="{% url 'app_auth:logout' %}">Logout</a>
                <a class="nav-link" href="{% url 'app_auth:signup' %}">Register</a>
                <a class="nav-link" href="{% url 'app_auth:signin' %}">Login</a>
            </p>
        </div>
    </div>

    {% block content %}
    {% endblock %}

</div>
</body>
</html>

quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}
{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope=""
             itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}/">{{tag}}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %}disabled{% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %}disabled{% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">>
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}